Reduce string copies in Source
zesterer/ariadne pull request #89
Opened 2023-09-29 08:47 UTC by goto-bus-stop

The `Source` structure stores an owned `String` for each individual line. This can cause many allocations for large documents. We regularly deal with 65 000 lines or more that only have a handful of diagnostics.

This PR makes two changes:
1. It separates string storage and line storage, `Line{}` now only contains indices into the string. Both character and byte indices are calculated in `Source::from` so the string storage can be sliced efficiently. You now have to go through `Source::get_line_text(Line)` to get the source text for a line. This commit still copies the text into `Source` but it does it in one allocation.
1. It makes `Source` generic over the string storage. This does add some complexity, as the genericity also requires having an associated string storage type on `Cache` implementations. But, it lets you use `Arc<str>` as a storage type to avoid having to copy the whole source text into ariadne, or even `&str` if you can guarantee the lifetime. The `FileCache` now no longer copies each file's contents immediately after reading it. The `sources()` function will use string references if possible. Only users of custom caches should be affected by this change.

With these changes you can use ariadne without copying any strings, the only allocation is for computing line offsets (and for individual diagnostics of course).

2023-09-29 11:03 UTC, zesterer requested changes
Thanks, this is a brilliant change! Just one small suggestion. It's a shame that default associated types aren't stable, since this could have been a semver-compliant change (`type Storage = String;`).

2023-09-29 11:03 UTC, zesterer commented on src/source.rs
> +pub struct Source<I: AsRef<str>> {
Perhaps `I` could be defaulted to `String`? That seems to almost always be the most sensible option.

2023-09-29 11:18 UTC, goto-bus-stop commented
Yeah I started out with `type Storage = String` and got yelled at 🥲 

Defaulting to String makes sense, mostly eases the upgrade path a bit for people currently writing `Source` in return types or struct fields.

2023-09-29 11:41 UTC, zesterer commented
Thanks very much for the PR!

2023-09-29 11:41 UTC, merged

2023-09-29 11:45 UTC, goto-bus-stop commented
thanks for reviewing so fast! 🤩

2023-09-29 18:23 UTC, zesterer commented
Were you looking for a release with this in the near term, or are you ok to wait for a while?

2023-09-30 09:18 UTC, goto-bus-stop commented
It's not critical, so please pick as you see fit :)